title: "Ekagrit Ventures"
description: "Tatvaâ€™s public research and finance notebook"
url: "https://ekagritventures.github.io"
repository: "ekagritventures/ekagritventures.github.io"
theme: minima
permalink: /:slug/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-mentions
exclude:
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - vendor
  - _internal
  - _templates
  - .jekyll-cache
  - .ruby-lsp
  - .DS_Store

collections:
  posts:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default

# Google Analytics (replace with your GA4 Measurement ID)
google_analytics: "G-8PRNH9GG8M"


